# Generated by Django 6.1.1 on 2026-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_venue_paper_venue_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cited_by_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='counts_by_year',
            field=models.JSONField(default=list),
        ),
    ]
