# Generated by Django 6.1.1 on 2026-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_cited_by_count_paper_counts_by_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='h_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='h_index_normalized',
            field=models.FloatField(default=0.0),
        ),
    ]
