# Generated by Django 6.1.1 on 2026-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_author_h_index_author_h_index_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation_velocity',
            field=models.FloatField(default=0.0),
        ),
    ]
