# Generated by Django 6.1.1 on 2026-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_citation_velocity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_reputation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paper',
            name='combined_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paper',
            name='velocity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
