# Generated by Django 6.1.1 on 2026-09-08 18:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_paper_author_reputation_score_paper_combined_score_and_more'),
        # The `vector` Postgres extension must exist before a `vector(768)`
        # column can be created -- pgvector_setup's initial migration
        # (#3) is what runs `CreateExtension("vector")`. Nothing forced
        # this ordering before this migration, since no prior `papers`
        # migration used `VectorField`.
        ('pgvector_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
