# Generated by Django 6.1.1 on 2026-09-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_paper_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='influential_citation_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paper',
            name='influential_citation_score',
            field=models.FloatField(default=0.0),
        ),
    ]
