# Generated by Django 6.1.1 on 2026-09-07 20:56

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgvector_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorSmokeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3)),
            ],
        ),
    ]
